packages:
  - apps/*
  - packages/*

allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  argon2: true
  cpu-features: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  sharp: true
  ssh2: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - argon2
  - cpu-features
  - esbuild
  - msgpackr-extract
  - prisma
  - protobufjs
  - sharp
  - ssh2
